### ISSUE TITLE
Crash when deleting rides

### ISSUE THREAD

**Issue by jonbev** [GoldenCheetah/GoldenCheetah#1234]
I get a crash everytime I try to delete a ride using a commit from a few days ago. Building latest now to check.

Also crashes when trying to split but I guess its the same issue as it is trying to remove the original.

**Comment by liversedge** [comment]
i fixed delete rides during refresh on the 7th. dc8cb24f43b099d

**Comment by jonbev** [comment]
Just built from the latest commit and it still crashes on delete for me.

**Comment by liversedge** [comment]
is that during a refresh ?

can you video to show me how it occurs ?

**Comment by liversedge** [comment]
better still gdb bt ?

**Comment by jonbev** [comment]
Never used gdb before but is this useful?

warning: ASSERT: "last >= first" in file itemmodels\qabstractitemmodel.cpp, line 2656

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: LEAK: 593 RenderObject

warning: LEAK: 4 Page

warning: LEAK: 4 Frame

warning: LEAK: 1044 WebCoreNode

warning: QWaitCondition: Destroyed while threads are still waiting

[Inferior 1 (process 12184) exited with code 03]

**Comment by liversedge** [comment]
LOL Not hugely - although it tells me its in a model.
If you run from gdb when back at the (gdb) prompt the "bt" command will give a stack back trace that IS useful :)

Also, when you delete do you have any rides left ?

**Comment by jonbev** [comment]
I get "no stack" when i do bt.

I have lots of rides left Its also not the top or bottom one in the list.

**Comment by liversedge** [comment]
You’re not building with debug I guess.
What version of QT are you using?

I cannot recreate this problem.

Mark

**Comment by liversedge** [comment]
can you make clean; qmake; make
i think its the .y again.

**Comment by liversedge** [comment]
I just pushed an update that might help, can you check ?

**Comment by jonbev** [comment]
Sorted with that commit thanks Mark.

**Comment by liversedge** [comment]
Excellent. Weird that it didn't affect others. I'm guessing your QT is pre QT5 .

**Comment by jonbev** [comment]
Qt5.3 on Windows......

**Comment by Joern-R** [comment]
Which QT 5.3.x exactly ? I have been using 5.3.2 since it's available and did also check if I get the same error - which was not the case. Since a few month I am not using the pre-build versions from QT any more, but the ones provided here: http://tver-soft.org/qt64

Available in 32bit/64bit - with a proper MingGW as part of the Installer and all relevant .DLLs. Very convenient to use. QTCreator is available separately as well.

I am currently using the SJLJ exception handling variant (in both 32 and 64bit) with OPENGL (no Angle). Which works fine with VLC for Video. (QT 5 video on Windows is very limited in formats - does not even play MP4 for me).
