### ISSUE TITLE
Release Candidate 1X BUG REPORTS

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1417]
* Drag and drop a season into the compare pane sets the season blank Windows 64 bit on Win 7
* Drag and drop an interval into the compare pane removes the interval from the tree !

**Comment by liversedge** [comment]
From Mark Liversedge:

Drag and drop an interval into the compare pane removes the interval from the tree !

**Comment by liversedge** [comment]
From Mark Liversedge:

*sigh*

It looks like QT 5.4.2 introduced a bug on QTreeView and drag and drop, its fixed in 5.5....

**Comment by Joern-R** [comment]
Just compiled with 5.5.0 RC (which is available since yesterday) - Win 32. Both Errors 
- Drag/Drop Season
- Drap/Drop Interval 
above still appear.

**Comment by liversedge** [comment]
great. sometimes qt is a royal pain.

**Comment by liversedge** [comment]
Crash when time goes bacwards. Fixed in b03420b7bb6aa50654457b4b96f0da5245423805

**Comment by liversedge** [comment]
Oversight in moxy metrics; there is an Average smO2 but not average tHb

**Comment by liversedge** [comment]
Should be able to configure which type of intervals are autodiscovered.

**Comment by liversedge** [comment]
When ridefile samples are adjusted to start from 0 seconds the intervals are not adjusted accordingly .. this leads to intervals that are off by at least 1 second.

**Comment by liversedge** [comment]
TP synchronisation keyboard shortcut Ctl-L has been lost.
Dialog is always too small.

**Comment by liversedge** [comment]
We should test a build with 5.5.0 .. and we should also consider some test automation!

**Comment by amtriathlon** [comment]
Intervals are misaligned, which is clearly visible in lap swimming files (Manual, TCX and PWX).

**Comment by amtriathlon** [comment]
Model estimates don't refresh when adding new rides, steps to reproduce the issue:
I started with a new athlete from scratch:
1) added a single ride with power data, no model data is shown, even after restart, the code seems to require at least 2 rides but I don't understand the rationale and it is somewhat confusing since model estimates are present in CP chart with just 1 ride.
2) added a second ride with power data and model estimates continue to be N/A, after restart they match those of CP chart.

**Comment by liversedge** [comment]
~~Column Chooser ordered case sensitive and contains Zxxx and Xxxx names.~~ Fixed in c7d2981d92b22df61cec17e8bd270a5a9a9902a5

**Comment by liversedge** [comment]
Model Estimates need to be integrated into the RideCache refresh, but thats going to have to wait until v4.0. 

There are a few related issues including writing/reading to a backing store to save on recomputing them as well as caching the values selected for each ride to avoid aggregating the entire MMP data series.

In other words, the aggregation phase needs optimizing !

**Comment by liversedge** [comment]
~~Temperature conversion error for fahrenheit.~~ Fixed in 270dbfba0417fcabbb3d27d7c981b7a22de32358

**Comment by liversedge** [comment]
PMC values on Skiba plot differ between 3.1 and 3.2

**Comment by liversedge** [comment]
~~QT4.8 on Mac crashes;~~
```
Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   QtGui                         	0x000000010106d6d0 QAction::isChecked() const + 4
1   @BUNDLEIDENTIFIER@            	0x00000001002b9491 MainWindow::saveGCState(Context*) + 61
2   @BUNDLEIDENTIFIER@            	0x00000001002c4e3d MainWindow::MainWindow(QDir const&) + 21437
3   @BUNDLEIDENTIFIER@            	0x00000001005098c2 main + 5602
4   @BUNDLEIDENTIFIER@            	0x0000000100007654 start + 52
```
Fixed in c3ac435942f83ba69ec6549ac886577405b7dd13
