### ISSUE TITLE
GC 3.2 requires discreet GPU for OS X

### ISSUE THREAD

**Issue by bdb** [GoldenCheetah/GoldenCheetah#1655]
GC causes the OS to keep the discreet GPU active for as long as GC is running. On a laptop this causes serious battery drain for those that like to keep GC always running (me).

Apple has a bundle plist key that you can add to say the app is fine with the integrated GPU. For any Mac laptop released in the last 3 years, the Intel integrated GPU should provide plenty of power for GC's charts. In Xcode the human readable plist key name is "Supports Automatic Graphics Switching". The raw key name is NSSupportsAutomaticGraphicsSwitching.

Maybe this can be added for GC 3.3?

<img width="662" alt="screen shot 2015-11-11 at 8 18 34 pm" src="https://cloud.githubusercontent.com/assets/130739/11108972/6e8bf3aa-88b1-11e5-96d0-3dfe57f63bfe.png">

**Comment by liversedge** [comment]
Wow, thanks for digging into this. 

I found this article about how to control this in qmake http://fixall.online/since-qt-53-it-is-possible-by-using-special-key-in/1423033/ so will look to add it to 3.3.

**Comment by liversedge** [comment]
It looks like it was fixed by QT upstream of us, so should be ok in the next release, and also in the development build if you want to check it?

![screen shot 2015-11-12 at 09 47 55](https://cloud.githubusercontent.com/assets/142876/11118019/a7fcf546-8936-11e5-8391-35b0c73731ed.png)

https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.3-DEV9

**Comment by bdb** [comment]
Great. Thanks for the quick response.

**Comment by bdb** [comment]
Well, spoke too soon. The issue is still present in 3.3 dev. See attached screenshots. Note the bundle plist does not contain the key. I think you may need a machine that has a discreet GPU AND an integrated GPU to see a YES value in Activity Monitor. Basically that means a MacBook Pro (I'm using a 2012 MBP Retina).

<img width="850" alt="screen shot 2015-11-12 at 7 16 08 pm" src="https://cloud.githubusercontent.com/assets/130739/11136236/605d0b40-8972-11e5-8395-b4f2ff99e884.png">

<img width="326" alt="screen shot 2015-11-12 at 7 17 12 pm" src="https://cloud.githubusercontent.com/assets/130739/11136240/68068344-8972-11e5-96c0-f8a007a12f84.png">

**Comment by bdb** [comment]
I added the key to existing Info.plist template and tested. It worked.
