### ISSUE TITLE
Cadence not reset/cleared during multiple training sessions

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#2251]
When I use the trainer function the cadence value from the last session(s) are not reset/cleared.

![image](https://cloud.githubusercontent.com/assets/925347/21086927/f8c959f2-bfee-11e6-985b-b73ce405f3ad.png)

GC v3.4 Offical release on Windows 10 64bit.

**Comment by liversedge** [comment]
should have been fixed a while ago.

**Comment by amtriathlon** [comment]
It’s a trivial error still present, I will fix it:

`cadData->clear();`

Missing before:
https://github.com/GoldenCheetah/GoldenCheetah/blob/a0ed8d020fa4822df643ed9ce19d641beeaa4337/src/Train/ErgFilePlot.cpp#L549
