### ISSUE TITLE
Elevation in TCX Ignored by Strava

### ISSUE THREAD

**Issue by linalan** [GoldenCheetah/GoldenCheetah#2535]
The exported TCX file does not include device type info. This results in Strava ignoring all recorded elevation data and doing its own calculation based on their own Strava elevation basemap which can differ substantially from recorded elevation. 

Per info from here: https://strava.github.io/api/v3/uploads/

 ```
 <Creator>
    <Name>My Awesome App with barometer</Name>
  </Creator>

```
I exported a TCX file from Garmin Connect and copy/pasted the relevant <Creator> stanza into my GoldenCheetah created TCX file. Uploading this to Strava fixed the elevation issue. 

```
 <Creator xsi:type="Device_t">
        <Name>Edge 520</Name>
        <UnitId>3908513174</UnitId>
        <ProductID>2260</ProductID>
        <Version>
          <VersionMajor>8</VersionMajor>
          <VersionMinor>0</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
       </Version>
</Creator>

```
GoldenCheetah 3.4
Build ID: 3950

**Comment by stschake** [comment]
b2b3af4 added writing the creator in the TCX export

**Comment by Joern-R** [comment]
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/pull/2815

**Comment by cobase2010** [comment]
I am still seeing the problem as the exported TCX file doesn't specify a specific Garmin device name and ID. It only contains a generic creator tag like this: 
<Creator xsi:type="Device_t">
                <Name>Garmin TCX</Name>
                <UnitId>0</UnitId>
                <ProductId>20119</ProductId>
                <Version>
                    <VersionMajor>0</VersionMajor>
                    <VersionMinor>0</VersionMinor>
                    <BuildMajor>0</BuildMajor>
                    <BuildMinor>0</BuildMinor>
                </Version>
            </Creator>
I tried this on both 3.5 and 3.6 but with the same result.
