### ISSUE TITLE
Withings Scale import no longer works

### ISSUE THREAD

**Issue by bobsica** [GoldenCheetah/GoldenCheetah#2786]
On GoldenCheetah_v3.5-DEV1710_64bit_MacOS

Withings scale initially worked until 4 days ago. I get an error

> {"status":342,"error":"The signature (using Oauth) is invalid"}.

GC let's me reauthorize successfully with Withings (Nokia), but the error persists even after restarting.

Has something changed on Nokia's end?

**Comment by amtriathlon** [comment]
Yes, it's a known issue (https://github.com/GoldenCheetah/GoldenCheetah/issues/2764), it's fixed in the last dev build recently published (1802).

**Comment by bobsica** [comment]
Sorry to re-open this I am using 1802 and still get the following error (even after removing Withings account and restarting): 

> {"status":342,"error":"The signature (using Oauth) is invalid"}

I viewed [#2764](https://github.com/GoldenCheetah/GoldenCheetah/issues/2764) as you suggested but that didn't help. Is there anything I can do to help debug this?
