### ISSUE TITLE
Google Drive sync not working in Windows 3.5dev1806

### ISSUE THREAD

**Issue by PeeTeeH** [GoldenCheetah/GoldenCheetah#2926]
drive sync works in legacy 3.5 stable.
Trying to setup a Google Drive sync ALWAYS results in API error message.
drive.file
drive.appdata
drive
<img width="403" alt="2018-09-10 11_05_37-oauth" src="https://user-images.githubusercontent.com/37756000/45287841-8d8ce180-b4e9-11e8-8765-9d861ffbd204.png">

**Comment by liversedge** [comment]
this is fixed in 1806: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1806

**Comment by PeeTeeH** [comment]
I experience this error in GC3.5dev1806.
GC3.5 stable works with Google Drive without problems.
Error is NOT solved unless Google API limits access to only one app instance.
