### ISSUE TITLE
Enable Python Data Processors to be run in automatic mode

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4095]
Metadata handling functions, introduced by https://github.com/GoldenCheetah/GoldenCheetah/commit/9315b301d739feb2302de47a54a5699ecccb4818 and https://github.com/GoldenCheetah/GoldenCheetah/commit/d7e1747a2b6e3493f9f50365768f7212cee92584, don't work when used in a Data Processor configured to run automatically on import or save.

Edit: the problem is more general than originally reported since read only access to metadata neither works in automatic mode.

**Comment by peret2000** [comment]
Maybe the issue is not specifically related to those functions, but to a wider problem, related with function [activityMetrics()](https://github.com/GoldenCheetah/GoldenCheetah/blob/4ae6dbea9358114f14595e3eb87727bd8ccebcb4/src/Python/SIP/Bindings.cpp#L990), that does not work properly in automatic processors or activity imports, and necessary to access metrics in Python (trough GC.activityMetrics())

The context that is arranged in [FixPyDataProcessor::postProcess()](https://github.com/GoldenCheetah/GoldenCheetah/blob/4ae6dbea9358114f14595e3eb87727bd8ccebcb4/src/FileIO/FixPyDataProcessor.cpp#L20) before calling [FixPyRunner::run()](https://github.com/GoldenCheetah/GoldenCheetah/blob/4ae6dbea9358114f14595e3eb87727bd8ccebcb4/src/FileIO/FixPyDataProcessor.cpp#L26) : it is explicitly set to null.
I guess that is done in such way because the context is pointing internally to the ride that is selected in the activity list, not to the one that is being imported or processed, so it would not work correctly

That context is passed to several methods, and when executing python code, it fails when accessing GC.activityMetrics(), as it is calling [Bindings::activityMetrics()](https://github.com/GoldenCheetah/GoldenCheetah/blob/4ae6dbea9358114f14595e3eb87727bd8ccebcb4/src/Python/SIP/Bindings.cpp#L990), that returns null.

I have been debugging the code, and come up with a possible solution, but I am not sure it is the best (even safe), as I do not know the architecture of the project (really huge and well designed, I am sure).
I am preparing a pull request, but please, if this comment sounds reasonable to you, it would be necessary that you, or some other expert, have a look to the code (very simple in the end) to determine if that change is worth and can be allowed. Sorry for that.

The 'workaround' has consisted on the trick of modifying 'context', whose RideFile property ('ride') points to the one selected in the activity list (not the one being imported or called in automatic postprocess). This is done in FixPyDataProcessor::postProcess(), creating a new RideItem.
Once the execution of the python code finishes, the original RideItem is restored, just in case it has implications (there are synchronization methods when it is changed, I have seen)

That RideItem is created but not configured at all, just using the correct RideFile object (that points to the ride being imported or called in postProcess). However, this trick seems to work: python code executes and modify tags, etc. Anyway, I am still testing it.

Let me do some tests and I will come to this issue with the pull request, unless you considerer this idea is dangerous, not safe, etc

Sorry the description of the execution flow, the design is complex to be followed from scratch, just debugging. BTW, QTCreator is really nice, mandatory for debugging

**Comment by amtriathlon** [comment]
> Maybe the issue is not specifically related to those functions, but to a wider problem, related with function [activityMetrics()](https://github.com/GoldenCheetah/GoldenCheetah/blob/4ae6dbea9358114f14595e3eb87727bd8ccebcb4/src/Python/SIP/Bindings.cpp#L990), that does not work properly in automatic processors or activity imports, and necessary to access metrics in Python (trough GC.activityMetrics())

You are right, when Python Data Processors were introduced (https://github.com/GoldenCheetah/GoldenCheetah/pull/2951) the functions accessing and manipulating activity data and were modified to support the automatic execution context:
https://github.com/GoldenCheetah/GoldenCheetah/blob/32b1f0f7d1cb9d88baec64f5865ee4de4ababd37/src/Python/SIP/Bindings.cpp#L654
But metadata and metrics access functions were not, and we would need to change this to fix the issue, instead of looking for a dangerous workaround.

**Comment by paulj49457** [comment]
I have fixed the Python processor importation issue and the explanation can be found in the pull request:  Python processor import fix, file import exclusion and file overwrite option #3770

**Comment by paulj49457** [comment]
I have fixed the Python processor importation issue and the explanation can be found in the pull request: Python import processing working #4236, on the existing structure within the RideFileImportWizard.

I also have a fix for the Python processor importation issue in a PR which contains two other changes and a restructuring of the import processing: Python processor import fix, file import exclusion and file overwrite option https://github.com/GoldenCheetah/GoldenCheetah/pull/3770

I suggest #4236 is considered for v3.6, while #3770 would be a nice addition to v3.6+

**Comment by amtriathlon** [comment]
I’ve taken a new look at this problem and I think it is not necessary or convenient to change RideImportWizard, besides doing so doesn’t fix the problem when the Python DP is invoked from a filter or a Python DP.
The analysis of @peret2000 above is basically correct, but instead of creating a new RideItem we can get Context from the RideFile and search the RideCache to find the corresponding RideItem to set in ScriptContext, that should fix activityMetrics. Additionally setTag/hasTag/delTag needs to look at item in ScriptContext before considering the currently selected item, just like activityMetrics does.
I will do some tests in the next few days since I isolated due to Covid-19 and have some free time.

**Comment by amtriathlon** [comment]
Finally I got the time to look at this in more detail, details are in the PR but the idea is DPs running on import cannot depend on RideCache data, so a new API getTag was added to be used in this context instead of activityMetrics, and notifications used for the remaining cases.
I am not willing to restructure RideImportWizard (and CloudService, which does a similar thing) to fix this issue, attending to https://github.com/GoldenCheetah/GoldenCheetah/wiki/Guidelines-for-submitting-a-patch#5-consider-the-chestertons-fence
Thank you for the discussion above, testing and feedback is welcome before merging and updating the docs.

**Comment by MeisterP** [comment]
> testing and feedback is welcome before merging and updating the docs

Using `GC.postProcess("some pyfix")` from within another `pyfix` works again. Much appreciated.
