### ISSUE TITLE
Withing Error retrieving token

### ISSUE THREAD

**Issue by wells240** [GoldenCheetah/GoldenCheetah#4162]
Cant get body measurement from Withing any more

Erreur lors de la récupération du token, Error transferring https://account.withings.com/oauth2/token? - server replied: Not Found (203)
[BREAKING] Shutting down access and refresh tokens endpoints
Shut Down Date: 02/08/2022
"https://support.withings.com//hc//en-us//articles//360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints"

**Comment by amtriathlon** [comment]
Every GC user with a withings scale will report this problem, without checking if is already fixed nor searching the forum?

**Comment by liversedge** [comment]
I've added a message to the download section of the website too.

**Comment by wells240** [comment]
Sorry if I duplicated the question but it was not without searching first. All the information I found was several years old.

Intuitively I had already installed V3.6 and the problem persists.

**Comment by wells240** [comment]
Finally managed to make the sync with Withing work. I had to uninstall and manually delete all files from all directories and reinstall the V3.6 dev.
