### ISSUE TITLE
git checkout fails on systems with symlink support (core.symlinks=true)

### ISSUE THREAD

**Issue by michaelprager** [GoldenCheetah/GoldenCheetah#4254]
When you try to clone this git repo on a system that supports symlinks (e.g. linux), git will fail to checkout with the following error message:

> error: unable to create symlink src/Resources/json/FITmetadata.json: File name too long
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.

This was initially reported here: https://aur.archlinux.org/packages/golden-cheetah-git#comment-876917
And I can confirm the issue. The following will work:

> git clone -c core.symlinks=false https://github.com/GoldenCheetah/GoldenCheetah

A fix to solve this upstream can be found here: https://stackoverflow.com/questions/18411200/git-unable-to-create-symlink-file-name-too-long

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/dc470ecf746fbb0f87146bbdb0a651301ca5040a

**Comment by michaelprager** [comment]
Sorry to insist, but the issue is only fixed on systems with core.symlink=false. It is still broken for core.symlink=true. This is because the file is still set to mode symlink instead of file. To fix the issue, the file needs to be deleted in a single commit and then recreated in a separate commit.

**Comment by michaelprager** [comment]
Confirmed working 👍
